# Functions for the FS(χ) property by Navarro: is the character field of χ 
# generated by a single character value?


"""
    is_fs_with_data(χ::Oscar.GAPGroupClassFunction)

Returns true iff the character field of χ is generated by a single character 
value. This function also returns a named tuple holding the character field, its degree, and the maximal degree of the subfield generated by character values.
"""
function is_fs_with_data(χ::Oscar.GAPGroupClassFunction)
    F, _ = character_field(χ)
    fdeg = degree(F)
    max_xdeg = 0

    for x in values(χ)
        xdeg = degree(minimal_polynomial(x))
        max_xdeg = max(max_xdeg, xdeg)

        if xdeg == fdeg
            return true, (
                char_field = F,
                char_field_degree = fdeg,
                max_value_degree = fdeg,
            )
        end
    end

    return false, (
        char_field = F,
        char_field_degree = fdeg,
        max_value_degree = max_xdeg,
    )
end

is_fs(χ::Oscar.GAPGroupClassFunction) =
    first(is_fs_with_data(χ))

function is_odd_degree(χ::Oscar.GAPGroupClassFunction)
    return is_odd(degree(ZZRingElem, χ))
end

function is_2rational(χ::Oscar.GAPGroupClassFunction)
    return is_odd(conductor(χ))
end

"""
    is_fs2_with_data(T::Oscar.GAPGroupCharacterTable; q=1, findall=false, ...)

Tests the FS₂ property on the character table `T`. For `q = 1`, the relevant
characters of `T` are tested directly. For a prime power `q > 1`, the test uses
the characters `χ = α ⊠ λ` of `G × C_{q^2}`, where `λ` is a faithful linear
character of `C_{q^2}` and `α` runs through the relevant characters of `T`, up
to Galois conjugacy.

Returns `(res, false_list)`, where `res` is `true` iff no failure was found and
`false_list` contains data for the failures. If `findall` is `false`, the search
stops after the first failure. Optional log files record failures and per-table
scan information.
"""
function is_fs2_with_data(
    T::Oscar.GAPGroupCharacterTable; 
    q::Integer=1, 
    findall=false,
    table_label::Union{Nothing,AbstractString}=nothing,
    findings_log_file::Union{Nothing,AbstractString}=nothing,
    scan_log_file::Union{Nothing,AbstractString}=nothing,
    metadata::NamedTuple=(;)
)

    if q != 1 && !_is_prime_power(q)
        throw(ArgumentError("q must be 1 or a prime power"))
    end

    false_list = NamedTuple[]

    # First create a candiate list of the alphas: odd degree or 
    # (q odd and conductor odd; the conductor of the direct product character
    # can only be off if q is odd).
    candidates = [ α for α in T if (is_odd_degree(α)) ]

    α_conductors = Dict()
    if is_odd(q)
        for α in T
            α in candidates && continue
            α_conductors[α] = conductor(α)
            if is_odd(α_conductors[α]) 
                push!(candidates, α)
            end
        end
    end

    candidates = galois_representatives(candidates)

    # Create the characters χ = α ⊠ λ for the candidate α
    if q > 1
        Cq2 = cyclic_group(q^2)
        TCq2 = character_table(Cq2)
        λ = first(χ for χ in TCq2 if is_faithful(χ))
        TH = character_table_direct_product(T, TCq2)
        χ = Dict(
            α => character_table_direct_product(TH, α, λ)
            for α in candidates
        )
    else
        χ = Dict(
            α => α
            for α in candidates
        )
    end
    
    if !isnothing(findings_log_file) || !isnothing(scan_log_file)
        group_data = (
            table = isnothing(table_label) ?
                identifier(T) :
                String(table_label),
            G_order = order(T),
            G_solvable = is_solvable(T),
        )
    end

    for α in candidates
        res, χ_data = is_fs_with_data(χ[α])

        if !res

            χ_conductor = conductor(χ[α])
            
            data = (
                q=q,
                α_position = findfirst(==(α), T),
                α_label = character_label(α),
                α_degree = degree(ZZRingElem, α),
                α_faithful = is_faithful(α),
                α_conductor = get(() -> conductor(α), α_conductors, α),
                α_char_field_degree=degree(character_field(α)[1]),
                χ_odd_degree = is_odd_degree(χ[α]),
                χ_two_rational = is_odd(χ_conductor),
                χ_conductor = χ_conductor,
                χ_char_field_degree = χ_data.char_field_degree,
                χ_max_value_degree = χ_data.max_value_degree,
            )

            push!(false_list, data)

            if !isnothing(findings_log_file)
                data = merge(data, group_data)

                data = reorder_fields(
                    data,
                    (
                        :table,
                        :G_order,
                        :q,
                        :α_position,
                        :α_label,
                        :α_degree,
                        :α_faithful,
                        :α_conductor,
                        :α_char_field_degree,
                        :χ_odd_degree,
                        :χ_two_rational,
                        :χ_conductor,
                        :χ_char_field_degree,
                        :χ_max_value_degree,
                        :G_solvable
                    ),
                ) 
                
                append_csv_row(
                    findings_log_file,
                    data,
                    metadata=metadata,
                )
            end

            if !findall
                break
            end
        end
    end

    if !isnothing(scan_log_file)
        process_data = ( 
            false_characters = length(false_list),
            findall = findall
        )
        append_csv_row(
            scan_log_file,
            merge(group_data, process_data),
            metadata=metadata,
        )
    end

    return length(false_list) == 0, false_list 

end


function is_fs2(
    T::Oscar.GAPGroupCharacterTable; 
    q::Integer=1
)

    res, _ = is_fs2_with_data(T; q=q, findall=false)

    return res

end

"""
    scan_ctbllib_fs2(; q=1, show_progress=true, findall=true, log_dir=nothing, metadata=(;))

Scans all non-duplicate ordinary character tables in the GAP Character Table
Library for failures of the FS₂ test performed by [`is_fs2_with_data`](@ref).
Tables are processed in sorted name order. If `log_dir` is given, findings and
per-table scan data are written below a scan-specific subdirectory of `log_dir`.
"""
function scan_ctbllib_fs2(; 
    q::Integer=1, 
    show_progress=true, 
    findall=true,
    log_dir::Union{Nothing,AbstractString}=nothing,
    metadata::NamedTuple=(;)
)
    
    # Avoid duplicate tables
    names = sort(String.(
        GAP.Globals.AllCharacterTableNames(
            GAP.Globals.IsDuplicateTable,
            false,
        )
    ))

    scan_id = "ctbllib-fs2-q" * string(q) * (findall ? "-findall" : "")

    findings_log_file = nothing
    scan_log_file = nothing
    if !isnothing(log_dir) 
        findings_log_file = joinpath(log_dir, scan_id, "findings.csv")

        scan_log_file = joinpath(log_dir, scan_id, "scan.csv")
    end

    false_counter = 0
    p = show_progress ? Progress(length(names); desc=scan_id) : nothing
    
    if !isnothing(log_dir) 
        metadata = merge(metadata, 
            log_metadata(
                packages=(
                    oscar=Oscar,
                ),
                extra=(
                    fs2_git_revision=git_revision(FS2),
                    gap_version=String(GAP.Globals.GAPInfo.Version),
                    ctbllib_version=_gap_package_version("ctbllib"),
                    scan_id = scan_id,
                    scan_total = length(names),
                ),
            )
        )
    end

    for (scan_index, name) in enumerate(names)
        T = character_table(name)

        metadata = merge(
            metadata,
            (scan_index = scan_index,),
        )

        res, T_false = is_fs2_with_data(
            T; 
            q=q, 
            findall=findall, 
            findings_log_file=findings_log_file, 
            scan_log_file=scan_log_file,
            metadata=metadata)
            false_counter = false_counter + length(T_false)

        if show_progress
            next!(p; showvalues=[
                (:table, name),
                (:false, false_counter),
            ])
        end

    end

end


"""
    scan_smallgroups_fs2(orders::AbstractUnitRange{<:Integer}; q=1, show_progress=true,
                         findall=true, log_dir=nothing, metadata=(;))

Scans the GAP SmallGroups library for all groups whose orders lie in `orders`.
Prime-power orders are skipped, since FS₂ holds for p-groups. Each remaining
group is tested with [`is_fs2_with_data`](@ref). If `log_dir` is given, findings
and per-group scan data are written below a scan-specific subdirectory of
`log_dir`.
"""
function scan_smallgroups_fs2(
    orders::AbstractUnitRange{<:Integer};
    q::Integer=1, 
    show_progress=true, 
    findall=true,
    log_dir::Union{Nothing,AbstractString}=nothing,
    metadata::NamedTuple=(;)
)
    
    # We can filter out prime powers because here FS_2 holds
    orders_filtered = [ n for n in orders if !_is_prime_power(n) ]

    for n in orders_filtered
        if !has_small_groups(n) 
            throw(ArgumentError(
                "groups of order $n are not available in the SmallGroups library",
            ))
        end
    end

    num_groups = Int(total_number_of_small_groups(orders_filtered))

    @info "Number of groups: "*string(num_groups)

    scan_id = "smallgroups-"*string(first(orders))*"-"*string(last(orders))*"-fs2-q" * string(q) * (findall ? "-findall" : "")

    findings_log_file = nothing
    scan_log_file = nothing
    if !isnothing(log_dir) 
        findings_log_file = joinpath(log_dir, scan_id, "findings.csv")

        scan_log_file = joinpath(log_dir, scan_id, "scan.csv")
    end

    false_counter = 0
    p = show_progress ? Progress(num_groups; desc=scan_id) : nothing
    
    if !isnothing(log_dir) 
        metadata = merge(metadata, 
            log_metadata(
                packages=(
                    oscar=Oscar,
                ),
                extra=(
                    fs2_git_revision=git_revision(FS2),
                    gap_version=String(GAP.Globals.GAPInfo.Version),
                    scan_id = scan_id,
                    scan_total = num_groups,
                ),
            )
        )
    end

    scan_index = 0
    for n in orders_filtered
        for i in 1:number_of_small_groups(n)
            scan_index += 1

            G = small_group(n, i)
            T = character_table(G)

            metadata = merge(
                metadata,
                (scan_index = scan_index, group_id = (n,i),),
            )

            res, T_false = is_fs2_with_data(
                T; 
                q=q, 
                findall=findall, 
                findings_log_file=findings_log_file, scan_log_file=scan_log_file,
                table_label="("*string(n)*","*string(i)*")",
                metadata=metadata)
                false_counter = false_counter + length(T_false)

            if show_progress
                next!(p; showvalues=[
                    (:group, (n,i)),
                    (:false, false_counter),
                ])
            end
        end
    end
end
