# Functions for the FS(χ) property by Navarr: is the character field of χ 
# generated by a single character value?


"""
    is_fs_with_data(χ::Oscar.GAPGroupClassFunction)

Returns true iff the character field of χ is generated by a single character 
value. This function also returns a named tuple holding the character field, its degree, and the maximal degree of the subfield generated by character values.
"""
function is_fs_with_data(χ::Oscar.GAPGroupClassFunction)
    F, _ = character_field(χ)
    fdeg = degree(F)
    max_xdeg = 0

    for x in values(χ)
        xdeg = degree(minimal_polynomial(x))
        max_xdeg = max(max_xdeg, xdeg)

        if xdeg == fdeg
            return true, (
                char_field = F,
                char_field_degree = fdeg,
                max_value_degree = fdeg,
            )
        end
    end

    return false, (
        char_field = F,
        char_field_degree = fdeg,
        max_value_degree = max_xdeg,
    )
end

is_fs(χ::Oscar.GAPGroupClassFunction) =
    first(is_fs_with_data(χ))

function is_odd_degree(χ::Oscar.GAPGroupClassFunction)
    return is_odd(degree(ZZRingElem, χ))
end

function is_2rational(χ::Oscar.GAPGroupClassFunction)
    return is_odd(conductor(χ))
end

function is_fs2_with_data(
    T::Oscar.GAPGroupCharacterTable; 
    q::Integer=1, 
    findall=false,
    table_label::Union{Nothing,AbstractString}=nothing,
    findings_log_file::Union{Nothing,AbstractString}=nothing,
    scan_log_file::Union{Nothing,AbstractString}=nothing,
    metadata::NamedTuple=(;)
)

    if q != 1 && !is_prime_power(q)
        throw(ArgumentError("q must be 1 or a prime power"))
    end

    false_list = NamedTuple[]

    # First create a candiate list of the alphas: odd degree or 
    # (q odd and conductor odd; the conductor of the direct product character
    # can only be off if q is odd).
    candidates = [ α for α in T if (is_odd_degree(α)) ]

    α_conductors = Dict()
    if is_odd(q)
        for α in T
            α in candidates && continue
            α_conductors[α] = conductor(α)
            if is_odd(α_conductors[α]) 
                push!(candidates, α)
            end
        end
    end

    candidates = galois_representatives(candidates)

    # Create the characters χ = α ⊠ λ for the candidate α
    if q > 1
        Cq2 = cyclic_group(q^2)
        TCq2 = character_table(Cq2)
        λ = first(χ for χ in TCq2 if is_faithful(χ))
        TH = direct_product(T, TCq2)
        χ = Dict(
            α => direct_product(TH, α, λ)
            for α in candidates
        )
    else
        χ = Dict(
            α => α
            for α in candidates
        )
    end
    
    if !isnothing(findings_log_file) || !isnothing(scan_log_file)
        group_data = (
            table = isnothing(table_label) ?
                identifier(T) :
                String(table_label),
            G_order = order(T),
            G_solvable = is_solvable(T),
        )
    end

    for α in candidates
        res, χ_data = is_fs_with_data(χ[α])

        if !res

            χ_conductor = conductor(χ[α])
            
            data = (
                q=q,
                α_position = findfirst(==(α), T),
                α_label = character_label(α),
                α_degree = degree(ZZRingElem, α),
                α_faithful = is_faithful(α),
                α_conductor = get(() -> conductor(α), α_conductors, α),
                α_char_field_degree=degree(character_field(α)[1]),
                χ_odd_degree = is_odd_degree(χ[α]),
                χ_two_rational = is_odd(χ_conductor),
                χ_conductor = χ_conductor,
                χ_char_field_degree = χ_data.char_field_degree,
                χ_max_value_degree = χ_data.max_value_degree,
            )

            push!(false_list, data)

            if !isnothing(findings_log_file)
                data = merge(data, group_data)

                data = reorder_fields(
                    data,
                    (
                        :table,
                        :G_order,
                        :q,
                        :α_position,
                        :α_label,
                        :α_degree,
                        :α_faithful,
                        :α_conductor,
                        :α_char_field_degree,
                        :χ_odd_degree,
                        :χ_two_rational,
                        :χ_conductor,
                        :χ_char_field_degree,
                        :χ_max_value_degree,
                        :G_solvable
                    ),
                ) 
                
                append_csv_row(
                    findings_log_file,
                    data,
                    metadata=metadata,
                )
            end

            if !findall
                break
            end
        end
    end

    if !isnothing(scan_log_file)
        process_data = ( 
            false_characters = length(false_list),
            findall = findall
        )
        append_csv_row(
            scan_log_file,
            merge(group_data, process_data),
            metadata=metadata,
        )
    end

    return length(false_list) == 0, false_list 

end


function is_fs2(
    T::Oscar.GAPGroupCharacterTable; 
    q::Integer=1
)

    res, _ = is_fs2_with_data(T; q=q, findall=false)

    return res

end

function scan_ctbllib_fs2(; 
    q::Integer=1, 
    show_progress=true, 
    findall=true,
    log_dir::Union{Nothing,AbstractString}=nothing,
    metadata::NamedTuple=(;)
)
    
    # Avoid duplicate tables
    names = sort(String.(
        GAP.Globals.AllCharacterTableNames(
            GAP.Globals.IsDuplicateTable,
            false,
        )
    ))

    scan_id = "ctbllib-fs2-q" * string(q) * (findall ? "-findall" : "")

    if !isnothing(log_dir) 
        findings_log_file = joinpath(log_dir, scan_id, "findings.csv")

        scan_log_file = joinpath(log_dir, scan_id, "scan.csv")
    end

    false_counter = 0
    p = Progress(length(names); desc=scan_id)
    
    if !isnothing(log_dir) 
        metadata = merge(metadata, 
            log_metadata(
                packages=(
                    oscar=Oscar,
                ),
                extra=(
                    fs2_git_revision=git_revision(FS2),
                    gap_version=String(GAP.Globals.GAPInfo.Version),
                    ctbllib_version=_gap_package_version("ctbllib"),
                    scan_id = scan_id,
                ),
                scan_total = length(names),
            )
        )
    end

    for name in names
        T = character_table(name)

        metadata = merge(
            metadata,
            (scan_index = p.counter,),
        )

        res, T_false = is_fs2_with_data(
            T; 
            q=q, 
            findall=findall, 
            findings_log_file=findings_log_file, scan_log_file=scan_log_file,
            metadata=metadata)
            false_counter = false_counter + length(T_false)

        if show_progress
            next!(p; showvalues=[
                (:table, name),
                (:false, false_counter),
            ])
        end

    end

end

function scan_smallgroups_fs2(
    n::Integer;
    q::Integer=1,
    show_progress=true,
    findall=true,
    log_file::Union{Nothing,AbstractString}=nothing,
    base_metadata::NamedTuple=(;),

    # Internal keywords used by the range method.
    _progress=nothing,
    _false_counter=Ref(0),
)
    n > 0 ||
        throw(ArgumentError("the group order must be positive"))

    has_small_groups(n) ||
        throw(ArgumentError(
            "groups of order $n are not available in the SmallGroups library",
        ))

    # p-groups satisfy FS2!
    if is_prime_power(n)
        return (
            order = Int(n),
            groups_scanned = 0,
            failures_recorded = 0,
        )
    end

    ngroups = Int(number_of_small_groups(n))
    order_false_counter = 0

    # A standalone fixed-order scan gets its own progress meter.
    # A range scan passes a shared progress meter through _progress.
    p = if !isnothing(_progress)
        _progress
    elseif show_progress
        Progress(
            ngroups;
            desc="Scanning SmallGroups order $n",
        )
    else
        nothing
    end

    # When called by the range method, base_metadata already contains
    # the range scan_kind and must not be replaced.
    if !isnothing(log_file) &&
       !(:scan_kind in keys(base_metadata))

        base_metadata = merge(
            base_metadata,
            log_metadata(
                packages=(
                    oscar=Oscar,
                ),
                extra=(
                    gap_version=
                        String(GAP.Globals.GAPInfo.Version),
                    smallgrp_version=
                        _gap_package_version("smallgrp"),
                    scan_kind=
                        "smallgroups-order-q$(q)",
                    order_min=Int(n),
                    order_max=Int(n),
                    groups_total=ngroups,
                    findall=findall,
                ),
            ),
        )
    end

    for i in 1:ngroups
        G = small_group(n, i)
        T = character_table(G)

        _, T_false = is_fs2_with_data(
            T;
            q=q,
            findall=findall,
            log_file=log_file,
            table_label="SmallGroup($n,$i)",
            base_metadata=base_metadata,
        )

        number_false = length(T_false)
        order_false_counter += number_false
        _false_counter[] += number_false

        if !isnothing(p)
            next!(
                p;
                showvalues=[
                    (:group, "SmallGroup($n,$i)"),
                    (:false, _false_counter[]),
                ],
            )
        end
    end

    return (
        order=Int(n),
        groups_scanned=ngroups,
        failures_recorded=order_false_counter,
    )
end


function scan_smallgroups_fs2(
    orders::AbstractUnitRange{<:Integer};
    q::Integer=1,
    show_progress=true,
    findall=true,
    log_file::Union{Nothing,AbstractString}=nothing,
    base_metadata::NamedTuple=(;),
)
    isempty(orders) &&
        throw(ArgumentError("the order range must be nonempty"))

    first(orders) > 0 ||
        throw(ArgumentError("all group orders must be positive"))

    unavailable = [
        n for n in orders
        if !has_small_groups(n)
    ]

    isempty(unavailable) ||
        throw(ArgumentError(
            "groups are not available in the SmallGroups library " *
            "for the following order(s): " *
            join(string.(unavailable), ", "),
        ))

    orders_to_scan = [
        n for n in orders
        if !is_prime_power(n)
    ]

    total_groups = sum(
        Int(number_of_small_groups(n))
        for n in orders_to_scan
    )

    p = show_progress ?
        Progress(
            total_groups;
            desc=(
                "Scanning SmallGroups orders " *
                "$(first(orders)):$(last(orders))"
            ),
        ) :
        nothing

    false_counter = Ref(0)

    if !isnothing(log_file)
        base_metadata = merge(
            base_metadata,
            log_metadata(
                packages=(
                    oscar=Oscar,
                ),
                extra=(
                    gap_version=
                        String(GAP.Globals.GAPInfo.Version),
                    smallgrp_version=
                        _gap_package_version("smallgrp"),
                    scan_kind=
                        "smallgroups-range-q$(q)",
                    order_min=Int(first(orders)),
                    order_max=Int(last(orders)),
                    groups_total=total_groups,
                    findall=findall,
                ),
            ),
        )
    end

    for n in orders
        scan_smallgroups_fs2(
            n;
            q=q,
            show_progress=false,
            findall=findall,
            log_file=log_file,
            base_metadata=base_metadata,
            _progress=p,
            _false_counter=false_counter,
        )
    end

    return (
        order_min=Int(first(orders)),
        order_max=Int(last(orders)),
        groups_scanned=total_groups,
        failures_recorded=false_counter[],
    )
end