# Returns true iff the character field of χ is generated by a 
# a single character value
function is_fs(χ::Oscar.GAPGroupClassFunction)
    
    F,_ = character_field(χ)
    fdeg = degree(F)
    for x in values(χ)
        xdeg = degree(minimal_polynomial(x))
        if xdeg == fdeg
            return true
        end
    end
    return false

end

function is_odd_degree(χ::Oscar.GAPGroupClassFunction)
    return is_odd(degree(ZZRingElem, χ))
end

function is_2rational(χ::Oscar.GAPGroupClassFunction)
    return is_odd(conductor(χ))
end

function is_fs2(T::Oscar.GAPGroupCharacterTable; q::Integer=1, findall=false)

    false_list = NamedTuple[]

    if q > 1
        Cq2 = cyclic_group(q^2)
        TCq2 = character_table(Cq2)
        λ = first(χ for χ in TCq2 if is_faithful(χ))
        TH = direct_product(T, TCq2)
        χ = Dict(
            α => direct_product(TH, α, λ)
            for α in T
        )
    else
        χ = Dict(
            α => α
            for α in T
        )
    end
    
    candidates = galois_representatives([ α for α in T if (is_odd_degree(α) || is_2rational(χ[α])) ])

    for α in candidates
        if !is_fs(χ[α])
            push!(false_list, (
                table=identifier(T),
                order=order(T),
                q=q,
                position = findfirst(==(α), T),
                label = character_label(α),
                degree = degree(α),
                odd_degree = is_odd_degree(α),
                two_rational = is_2rational(χ[α])
            ))
            if !findall
                return false, false_list
            end
        end
    end

    return length(false_list) == 0, false_list 

end

function scan_ctbllib_fs2(; 
    q::Integer=1, 
    show_progress=true, 
    findall=true,
    log_file::Union{Nothing,AbstractString}=nothing)
    
    names = String.(GAP.Globals.AllCharacterTableNames())
    false_list = []
    p = Progress(length(names); desc="Scanning CTblLib")

    for name in names
        T = character_table(name)

        res, T_false = is_fs2(T; q=q, findall=findall)
        append!(false_list, T_false)

        if !isnothing(log_file)

            for false_char in T_false
        
                metadata = log_metadata(
                    packages=(
                        oscar=Oscar,
                    ),
                    extra=(
                        gap_version=String(GAP.Globals.GAPInfo.Version),
                        ctbllib_version=_gap_package_version("ctbllib"),
                    
                    ),
                    system=false,
                    memory=false,
                )

                append_csv_row(
                    log_file,
                    false_char;
                    metadata=metadata,
                )
            end
        end

        if show_progress
            next!(p; showvalues=[
                (:table, name),
                (:false, length(false_list)),
            ])
        end

    end

end